# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobileApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileApp
  pod 'Firebase/Core'

  target 'mobileApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'mobileApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileApp-tvOS

 # target 'mobileApp-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
 # end

#end
