export const Colors = {
  Red: "#8C162A",
  Blue: "#033649",
  WhiteBG: "#ECF0F1",

  sub: {
    Cancelled: '#2ECC71',
    Substitution: '#03A9F4',
    RoomSwitch: '#00897B',
    Default: '#607D8B',
  },
}

export const Grades = ['5', '6', '7', '8', '9'];

// Definitely make this dynamic
export const Teachers = {
  An: "Anft",
  Ant: "Antel",
  Bch: "Bach",
  Ban: "Banhold",
  Ber: "Berhane",
  Bi: "Bickel",
  Bk: "Bock",
  Brw: "Breitwieser",
  Bt: "Best",
  Bts: "Bitsch",
  Ca: "Catta",
  Chr: "Christ",
  Ctz: "Cuntz",
  Dam: "Dammel",
  Den: "Denzer",
  Dl: "Düll",
  Dzi: "Dziedzic",
  Eck: "Eck",
  Eif: "Eifert",
  Eff: "Effenberger",
  Fra: "Franke",
  Fk: "Franke",
  Fü: "Füssler",
  GK: "Großmann-Kurzer",
  Gl: "Glanz",
  Gra: "Grabowski",
  Grf: "Graf",
  Gt: "Günter",
  Gü: "Günther",
  Ha: "Hartmann-Thierolf",
  Hen: "Henning",
  Hg: "Hosang",
  Hin: "Hinrichs",
  Hm: "Hammann",
  Hlg: "Holzgreve",
  Hu: "Huther",
  Hy: "Hyn",
  Jae: "Jaehnig",
  Jan: "Jankowiak",
  Kal: "Kaletta",
  Kai: "Kaiser",
  Kas: "Kasper",
  Ker: "Kern",
  Kor: "Korte",
  Kt: "Kottmann",
  Kd: "Kremendahl",
  Kü: "Kühn",
  Lan: "Landsiedel",
  Lo: "Lode",
  Lum: "Lumpe",
  Me: "Meja",
  Min: "Minor",
  Mc: "Mastrominico",
  Mz: "Melzer",
  Mh: "Meseth",
  Mon: "Montag",
  Mü: "Müller",
  Mv: "Mävers",
  No: "Nothacker",
  OE: "Orjollet-Ebel",
  Ott: "Otten",
  Ohl: "Ohl",
  Pf: "Pfaul",
  RK: "Rothenburger-Kavermann",
  Schä: "Schäfer",
  Schd: "Schöpsdau",
  Schl: "Schledt",
  Sbr: "Schreiber",
  Schö: "Schönfelder",
  Sdt: "Schmidt",
  SE: "Schirmaier-Ebert",
  Schü: "Schüttler",
  Sei: "Seibold",
  Sg: "Singer",
  Sl: "Scholler",
  Sim: "Simon",
  Sp: "Suppmann",
  Ste: "Steinke",
  Stk: "Storck",
  Swa: "Schwabach-Nehring",
  Tü: "Türke",
  Ts: "Tüshaus",
  Vol: "Vollmers",
  Vö: "Völker",
  Wd: "Waldmann",
  Wei: "Weilbächer",
  Wf: "Wolf",
  Zm: "Zemke",
};
  
export const API_URL = "http://sudocode.me:6767/api/v1/"